# -*- coding: utf-8 -*-
"""(Proyek Kompleks) – Sistem Manajemen Data Mahasiswa Menggunakan Binary Search Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dk2FncOopUDK8ygrmMdcV9oj0a-45MS8
"""

#Soal 5 (Proyek Kompleks) – Sistem Manajemen Data Mahasiswa Menggunakan Binary Search Tree
#Deskripsi

#Sebuah kampus ingin menyimpan data mahasiswa menggunakan Binary Search Tree berdasarkan NIM.

#Program harus memiliki menu:

#Tambah Mahasiswa
#Cari Mahasiswa
#Tampilkan Data Mahasiswa (Inorder)
#Hapus Mahasiswa
#Keluar

#Setiap mahasiswa memiliki:

#NIM
#Nama
#IPK
#Contoh Tampilan
#===== MENU =====
#1. Tambah Mahasiswa
#2. Cari Mahasiswa
#3. Tampilkan Mahasiswa
#4. Hapus Mahasiswa
#5. Keluar

#Pilihan : 1

#NIM : 23001
#Nama : Budi
#IPK : 3.75

#Data berhasil ditambahkan


class Mahasiswa:
    def __init__(self, nim, nama, ipk):
        self.nim = nim
        self.nama = nama
        self.ipk = ipk
        self.left = None
        self.right = None


class BST:
    def __init__(self):
        self.root = None

    # Tambah Data
    def tambah(self, root, nim, nama, ipk):
        if root is None:
            return Mahasiswa(nim, nama, ipk)

        if nim < root.nim:
            root.left = self.tambah(root.left, nim, nama, ipk)
        elif nim > root.nim:
            root.right = self.tambah(root.right, nim, nama, ipk)

        return root

    # Cari Data
    def cari(self, root, nim):
        if root is None:
            return None

        if nim == root.nim:
            return root

        if nim < root.nim:
            return self.cari(root.left, nim)
        else:
            return self.cari(root.right, nim)

    # Tampilkan Inorder
    def tampil(self, root):
        if root:
            self.tampil(root.left)
            print(
                f"NIM : {root.nim} | Nama : {root.nama} | IPK : {root.ipk}")
            self.tampil(root.right)

    # Cari node terkecil
    def minimum(self, root):
        while root.left:
            root = root.left
        return root

    # Hapus Data
    def hapus(self, root, nim):
        if root is None:
            return root

        if nim < root.nim:
            root.left = self.hapus(root.left, nim)

        elif nim > root.nim:
            root.right = self.hapus(root.right, nim)

        else:
            # Tidak punya anak kiri
            if root.left is None:
                return root.right

            # Tidak punya anak kanan
            elif root.right is None:
                return root.left

            # Punya dua anak
            temp = self.minimum(root.right)

            root.nim = temp.nim
            root.nama = temp.nama
            root.ipk = temp.ipk

            root.right = self.hapus(root.right, temp.nim)

        return root


# Program Utama
tree = BST()

while True:
    print("\n===== MENU =====")
    print("1. Tambah Mahasiswa")
    print("2. Cari Mahasiswa")
    print("3. Tampilkan Mahasiswa")
    print("4. Hapus Mahasiswa")
    print("5. Keluar")

    pilih = input("Pilihan : ")

    if pilih == "1":
        nim = int(input("NIM  : "))
        nama = input("Nama : ")
        ipk = float(input("IPK  : "))

        tree.root = tree.tambah(tree.root, nim, nama, ipk)

        print("Data berhasil ditambahkan")

    elif pilih == "2":
        nim = int(input("Masukkan NIM yang dicari : "))

        data = tree.cari(tree.root, nim)

        if data:
            print("\nData ditemukan")
            print("NIM  :", data.nim)
            print("Nama :", data.nama)
            print("IPK  :", data.ipk)
        else:
            print("Data tidak ditemukan")

    elif pilih == "3":
        print("\n===== DATA MAHASISWA =====")

        if tree.root is None:
            print("Belum ada data")
        else:
            tree.tampil(tree.root)

    elif pilih == "4":
        nim = int(input("Masukkan NIM yang akan dihapus : "))

        if tree.cari(tree.root, nim):
            tree.root = tree.hapus(tree.root, nim)
            print("Data berhasil dihapus")
        else:
            print("Data tidak ditemukan")

    elif pilih == "5":
        print("Program selesai")
        break

    else:
        print("Pilihan tidak valid")