# -*- coding: utf-8 -*-
"""Menentukan Tinggi (Height) Binary Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dk2FncOopUDK8ygrmMdcV9oj0a-45MS8
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

def tinggi(root):
    if root is None:
        return 0

    kiri = tinggi(root.left)
    kanan = tinggi(root.right)

    return 1 + max(kiri, kanan)

# Membuat tree
root = Node(1)

root.left = Node(2)
root.right = Node(3)

root.left.left = Node(4)
root.left.right = Node(5)

root.left.left.left = Node(6)
root.left.left.left.right = Node (5)


print("Tinggi tree =", tinggi(root))