# -*- coding: utf-8 -*-
"""Menghitung Jumlah Node pada Binary Tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dk2FncOopUDK8ygrmMdcV9oj0a-45MS8
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

def count_nodes(root):
    if root is None:
        return 0

    return 1 + count_nodes(root.left) + count_nodes(root.right)

# Membuat tree
root = Node(10)
root.left = Node(5)
root.right = Node(15)
root.left.left = Node(3)
root.left.right = Node(7)
root.left.right.left = Node(8)
root.left.right.right = Node(11)
root.left.right.right.right = Node (2)
root.left.right.right.right.right = Node (9)
root.left.right.right.right.right.right = Node (20)
root.left.right.right.right.right.right.right = Node (17)

print("Jumlah node =", count_nodes(root))