# -*- coding: utf-8 -*-
"""Pencarian Data pada Binary Search Tree (BST).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dk2FncOopUDK8ygrmMdcV9oj0a-45MS8
"""

#Soal 4 (Sedang) – Pencarian Data pada Binary Search Tree (BST)
#Deskripsi

#Buat program BST yang dapat mencari apakah suatu nilai terdapat dalam tree.

#Data BST
#          50
#        /    \
#      30      70
#     /  \    /  \
#   20   40 60   80
#Input
#60
#Output
#Data ditemukan
#Input
#90
#Output
#Data tidak ditemukan


class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

def cari(root, nilai):
    if root is None:
        return False

    if root.data == nilai:
        return True

    if nilai < root.data:
        return cari(root.left, nilai)
    else:
        return cari(root.right, nilai)

# Membuat BST
root = Node(50)

root.left = Node(30)
root.right = Node(70)

root.left.left = Node(20)
root.left.right = Node(40)

root.right.left = Node(60)
root.right.right = Node(80)

# Input data yang dicari
x = int(input("Masukkan nilai yang dicari: "))

if cari(root, x):
    print("Data ditemukan")
else:
    print("Data tidak ditemukan")